version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: laravel_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=rr_back
      - DB_USERNAME=admin
      - DB_PASSWORD=12345678
    ports:
      - "8080:8080"
  
  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: rr_back
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
